### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by davidyhall** [davidyhall/PlotMyTrot#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth UI

---
TODO: Bonus

- [x] Add `UserProperties` table for additional user information
- [x] Redesign /signup/ to require some additional user information.
- [x] Redesign auth to use `email` instead of `username`.
- Add selective-error UI for each form input.
- Perfect styling to `pixel-perfect`.

**Comment by mashuDuek** [comment]
Looking good! Comments below:

1. The navbar on /login and /signup is too centered, take a look at mapmyrun, on those routes, they move it to the left. 
2. The forms need to have a greater margin from the nav-bar, checkout mapmyrun. 
3. The sign-up form is supposed to request much more information from user, including date of birth email, etc. 
4. You need a demo login button. 
5. They put a nice blue border around the sing-in button once its clicked, or selected I believe. Check it out. 

For now thats good. Let me know when you complete those things and I'll check again.

**Comment by mashuDuek** [comment]
Great work, you can close this issue.
